package English.Instructions;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
public class SnakeAndLadderInstructions {
    public static void display()throws IOException, InterruptedException {
        long a;
        char b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        Thread.sleep(1500);
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("        ****      ****       ***      ****      ***       *** ***********                                                    ");
        System.out.println("     **********   *****      ***     ******     ***     ***   ***********                                                    ");
        System.out.println("   ****      **** ******     ***    ***  ***    ***   ***     ***                                                            ");
        System.out.println("   ****           *** ***    ***   ***    ***   *** ***       ***                                                            ");
        System.out.println("     ******       ***  ***   ***  ***      ***  *****         *******                                                        ");
        System.out.println("         ******   ***   ***  *** ************** *****         *******                                                        ");
        System.out.println("             **** ***    *** *** ************** *** ***       ***                                                            ");
        System.out.println("   ****      **** ***     ****** ***        *** ***   ***     ***                                                            ");
        System.out.println("     **********   ***      ***** ***        *** ***     ***   ***********                                                    ");
        System.out.println("        ****      ***       **** ***        *** ***       *** ***********                                                    ");
        Thread.sleep(1000);
        System.out.print('\u000C');
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("        ****      ****       ***      ****      ***       *** ***********            ****      ****       *** *********      ");
        System.out.println("     **********   *****      ***     ******     ***     ***   ***********           ******     *****      *** ***********    ");
        System.out.println("   ****      **** ******     ***    ***  ***    ***   ***     ***                  ***  ***    ******     *** ***      ****  ");
        System.out.println("   ****           *** ***    ***   ***    ***   *** ***       ***                 ***    ***   *** ***    *** ***        *** ");
        System.out.println("     ******       ***  ***   ***  ***      ***  *****         *******            ***      ***  ***  ***   *** ***        *** ");
        System.out.println("         ******   ***   ***  *** ************** *****         *******           ************** ***   ***  *** ***        *** ");
        System.out.println("             **** ***    *** *** ************** *** ***       ***               ************** ***    *** *** ***        *** ");
        System.out.println("   ****      **** ***     ****** ***        *** ***   ***     ***               ***        *** ***     ****** ***      ****  ");
        System.out.println("     **********   ***      ***** ***        *** ***     ***   ***********       ***        *** ***      ***** ***********    ");
        System.out.println("        ****      ***       **** ***        *** ***       *** ***********       ***        *** ***       **** *********      ");
        Thread.sleep(1000);
        System.out.print('\u000C');
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("                                                                                                                           ");
        System.out.println("        ****      ****       ***      ****      ***       *** ***********            ****      ****       *** *********      ");
        System.out.println("     **********   *****      ***     ******     ***     ***   ***********           ******     *****      *** ***********    ");
        System.out.println("   ****      **** ******     ***    ***  ***    ***   ***     ***                  ***  ***    ******     *** ***      ****  ");
        System.out.println("   ****           *** ***    ***   ***    ***   *** ***       ***                 ***    ***   *** ***    *** ***        *** ");
        System.out.println("     ******       ***  ***   ***  ***      ***  *****         *******            ***      ***  ***  ***   *** ***        *** ");
        System.out.println("         ******   ***   ***  *** ************** *****         *******           ************** ***   ***  *** ***        *** ");
        System.out.println("             **** ***    *** *** ************** *** ***       ***               ************** ***    *** *** ***        *** ");
        System.out.println("   ****      **** ***     ****** ***        *** ***   ***     ***               ***        *** ***     ****** ***      ****  ");
        System.out.println("     **********   ***      ***** ***        *** ***     ***   ***********       ***        *** ***      ***** ***********    ");
        System.out.println("        ****      ***       **** ***        *** ***       *** ***********       ***        *** ***       **** *********      ");
        System.out.println("                                                                                                                           ");
        System.out.println("                          ***              ****      *********      *********      *********** *********                   ");
        System.out.println("                          ***             ******     ***********    ***********    *********** ***********                 ");
        System.out.println("                          ***            ***  ***    ***      ****  ***      ****  ***         ***      ***                ");
        System.out.println("                          ***           ***    ***   ***        *** ***        *** ***         ***      ***                ");
        System.out.println("                          ***          ***      ***  ***        *** ***        *** *******     ***********                 ");
        System.out.println("                          ***         ************** ***        *** ***        *** *******     *********                   ");
        System.out.println("                          ***         ************** ***        *** ***        *** ***         ***    ****                 ");
        System.out.println("                          ***         ***        *** ***      ****  ***      ****  ***         ***      ***                ");
        System.out.println("                          *********** ***        *** ***********    ***********    *********** ***      ***                ");
        System.out.println("                          *********** ***        *** *********      *********      *********** ***      ***                ");
        System.out.println("                                                                                                                           ");
        Thread.sleep(1500);
        System.out.print("\t\t\t\t\t\tC");
        Thread.sleep(250);
        System.out.print("r");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("a");
        Thread.sleep(250);
        System.out.print("t");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("d ");
        Thread.sleep(250);
        System.out.print("b");
        Thread.sleep(250);
        System.out.print("y ");
        Thread.sleep(500);
        System.out.print("SS ");
        Thread.sleep(500);
        System.out.print("GAMING ");
        Thread.sleep(500);
        System.out.print("STUDIOS");
        Thread.sleep(1000);
        System.out.println("\n\t\t\t\t<Enter \'1\' to check instructions or any other character to skip>");
        try {
            b = br.readLine().charAt(0);
            System.out.print('\u000C');
            if(b == '1')
                instructions();
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Restarting the program. Please wait...");
            Thread.sleep(5000);
            System.out.print('\u000C');
        }
    }
    public static void instructions()throws IOException {
        long a;
        String b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
        System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        System.out.println("Snake and Ladder is a 4-players board game. The snake and ladder board is divided into a 10x10 grid, containing markings from ");
        System.out.println("1 to 100. The main objectives of the four players is to race against each other and reach 100 first. The players are provided ");
        System.out.println("with a dice. The number a player gets after rolling the dice is the number of houses his token moves forward. Players get their");
        System.out.println("chances one after another, in the order of RED, GREEN, YELLOW and BLUE. The zeroth position is the starting position, which is ");
        System.out.println("not included in the board. To get into the board, the players are required to score 1 in the dice, and once they enter the ");
        System.out.println("board, their tokens move as stated above. But the game is not that easy...");
        System.out.println("\nTo make the game a bit more difficult and interesting, the board contains some entities, the SNAKES and the LADDERS. The ");
        System.out.println("snakes are there to bring a player down, whereas the ladders promotes the player to a point. The snakes and the ladder may be ");
        System.out.println("present anywhere in the board. Once a player gets to the mouth of the snake, the token goes all over through the snakes\'s ");
        System.out.println("stomach and lands on the box where its tail end. Similarly, once a player reaches the base of a ladder, the token climbs up the ");
        System.out.println("ladder to the box, where its top reaches. The players need to get through all these challenges and reach the final destination.");
        System.out.println("The player to make it to the top first wins.");
        System.out.println("\n                                                   S                      <---+                              ");
        System.out.println("                               Snakes are shown    |                          |   Ladders are shown          ");
        System.out.println("                               as such line. S     |                          |   as such lines. L           ");
        System.out.println("                               denotes its head    |                          |   denotes its base           ");
        System.out.println("                               and the arrowhead   |                          |   and the arrowhead          ");
        System.out.println("                               denotes its tail    |                          |   denotes its top            ");
        System.out.println("                                                   +--->                      L                              ");
        System.out.print("\nEnter \'1\' to read next or any other number to skip : ");
        try {
            b = br.readLine();
            System.out.print('\u000C');
            if(b.equals("1")) {
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("              " + '\u24C7' + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nThis is a snake and ladder board. You can probably see the snakes and ladders around the board. The snakes are waiting for ");
                System.out.println("their pray. The players to land on the S will fall to the square where the line ends with an arrowhead. Similarly, if anyone ");
                System.out.println("lands on L, they will go up to the square where the ladder ends with an arrowhead.");
                Thread.sleep(30000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("              " + '\u24C7' + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                Thread.sleep(15000);
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |" + '\u24C7' + "      |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                Thread.sleep(1500);
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |" + '\u24C7' + "      |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                Thread.sleep(1000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |" + '\u24C7' + "      | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                Thread.sleep(1000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+-->     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        |" + '\u24C7' + "    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                Thread.sleep(1500);
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24CE' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                Thread.sleep(1500);
                System.out.println("\nNow, let YELLOW be on 15.");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+----" +  '\u24CE' + "--+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                Thread.sleep(1500);
                System.out.println("\nNow, let YELLOW be on 15. If it gets 2, this happens...");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+----" +  '\u24CE' + "--+--------+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                System.out.println("\nNow, let YELLOW be on 15. If it gets 2, this happens...");
                Thread.sleep(1000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +--" +  '\u24CE' + "--+--------+--------+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+-->     |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                System.out.println("\nNow, let YELLOW be on 15. If it gets 2, this happens...");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+--> " +  '\u24CE' + "  |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24B7');
                System.out.println("\nHave you noticed the tokens? They are outside the board. To enter into the board, you need to get 1 in the dice. Once you are ");
                System.out.println("in the board, you can move your token according to what you get in the dice.");
                System.out.println("\nFor example, if RED gets 1 now, then RED goes to 1. Watch the board...");
                System.out.println("Now, in its next turn, if it gets 3, watch the board...");
                System.out.println("Now observe that RED has landed in a ladder. The ladder will carry RED to 14.");
                System.out.println("\nNow, let YELLOW be on 15. If it gets 2, this happens...");
                Thread.sleep(1500);
                System.out.println("\nThe main aim of every player is to reach 100 before anyone else.");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t       SNAKE AND LADDER");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("             |        |        | S      |        |        |        |        |        | S    +-+-->     |");
                System.out.println("             |  100 +-+-> 99   | | 98   |   97   |   96   |   95   |   94   |   93   | | 92 | |   91   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+--------+--------+-+----+-+--------+");
                System.out.println("             |      | |        | |      |     <--+--------+--------+--------+-+      | |    | |        |");
                System.out.println("             |   81 | |   82   | | 83   |   84   |   85   |   86   | S 87   | | 88   | | 89 | |   90   |");
                System.out.println("             +------+-+--------+-+------+--------+--------+--------+-+------+-+------+-+----+-+--------+");
                System.out.println("             |      L |     <--+-+      |        |        |        | |      | |   <--+-+    L |        |");
                System.out.println("             |   80   |   79   |   78   |   77   |   76   |   75   | | 74   | | 73   |   72   |   71   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+-+------+-+------+--------+--------+");
                System.out.println("             |        |      S |        | S      |        |        | |   <--+-|------+--------|-+      |");
                System.out.println("             |   61   |   62 | |   63   | | 64   |   65   |   66   | | 67   | | 68   |   69   | | 70   |");
                System.out.println("             +--------+------+-+--------+-+------+--------+--------+-+------+-+------+--------+-+------+");
                System.out.println("             |     <--+------|-+--------+-+      |        |        | |    S | |      |        | L      |");
                System.out.println("             |   60   |   59 | |   58   |   57   |   56   |   55   | | 54 | | | 53   |   52   |   51   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      +-+-->   | |        |        |        |        | |    | | |      |        |        |");
                System.out.println("             |   41 | |   42 | |   43   |   44   |   45   |   46   | | 47 | | | 48   |   49   |   50   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+-+----+-+-+------+--------+--------+");
                System.out.println("             |      | |      | |        |        |     <--+--------+-+    | | |      |      +-+-->     |");
                System.out.println("             |   40 | |   39 | |   38   |   37   |   36   |   35   |   34 V | | 33   |   32 | |   31   |");
                System.out.println("             +------+-+------+-+--------+--------+--------+--------+--------+-+------+------+-+--------+");
                System.out.println("             |      L |      | |        |        |        |        |        | L      |      | |        |");
                System.out.println("             |   21   |   22 | |   23   |   24   |   25   |   26   |   27   |   28   |   29 | |   30   |");
                System.out.println("             +--------+------+-+--------+--------+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |      | |        | +------+--------+--------+" + '\u24C7' + ">     |        |      | |        |");
                System.out.println("             |   20   |   19 V |   18   | | 17 S |   16   |   15   |   14   |   13   |   12 | |   11   |");
                System.out.println("             +--------+--------+--------+-+----|-+--------+--------+--------+--------+------+-+--------+");
                System.out.println("             |        |        |        | L    +-+--------+--------+--> " +  '\u24CE' + "  |        |      L |        |");
                System.out.println("             |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |   10   |");
                System.out.println("             +--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+");
                System.out.println("                " + '\u24BC' + '\u24B7');
                System.out.println("\nNow I hope you have learnt the basics of the game. Enter any character to play the game : ");
                br.readLine();
                System.out.print('\u000C');
            }
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Please restart the program to interact...");
        }
    }
}
