package English.Instructions;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
public class SudokuInstructions {
    public static void display()throws IOException, InterruptedException {
        long a;
        char b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        Thread.sleep(1500);
        System.out.print("\n\n\n\n\n\n\n");
        System.out.println("           *****        ****          ****  **********              ********       ****            **** ****          ****");
        System.out.println("        ************    ****          ****  *************        **************    ****          ****   ****          ****");
        System.out.println("      *****       ****  ****          ****  ****     ******    ****          ****  ****        ****     ****          ****");
        System.out.println("      ****         **** ****          ****  ****        ****  ****            **** ****      ****       ****          ****");
        System.out.println("       ****             ****          ****  ****         **** ****            **** ****    ****         ****          ****");
        System.out.println("         ****           ****          ****  ****         **** ****            **** ****  ****           ****          ****");
        System.out.println("            *****       ****          ****  ****         **** ****            **** ********             ****          ****");
        System.out.println("                ****    ****          ****  ****         **** ****            **** ****  ****           ****          ****");
        System.out.println("                  ****  ****          ****  ****         **** ****            **** ****    ****         ****          ****");
        System.out.println("      ****         **** ****          ****  ****        ****  ****            **** ****      ****       ****          ****");
        System.out.println("       ****      *****   ****        ****   ****     ******    ****          ****  ****        ****      ****        ****");
        System.out.println("         ************      ************     *************        **************    ****          ****      ************");
        System.out.println("             *****            ******        **********              ********       ****            ****       ******");
        Thread.sleep(1500);
        System.out.print("\n\t\t\t\t\t\t C");
        Thread.sleep(250);
        System.out.print("r");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("a");
        Thread.sleep(250);
        System.out.print("t");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("d ");
        Thread.sleep(250);
        System.out.print("b");
        Thread.sleep(250);
        System.out.print("y ");
        Thread.sleep(500);
        System.out.print("SS ");
        Thread.sleep(500);
        System.out.print("GAMING ");
        Thread.sleep(500);
        System.out.print("STUDIOS");
        Thread.sleep(1000);
        System.out.println("\n\n\n\n\n\t\t\t\t<Enter \'1\' to check instructions or any other character to skip>");
        try {
            b = br.readLine().charAt(0);
            System.out.print('\u000C');
            if(b == '1')
                instructions();
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Restarting the program. Please wait...");
            Thread.sleep(5000);
            System.out.print('\u000C');
        }
    }
    public static void instructions()throws IOException {
        long a;
        String b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        System.out.println("\t\t\t\t\t\t            SUDOKU");
        System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        System.out.println("Sudoku is basically a number game. The board has 9 columns and 9 rows. It is further divided into 3x3 small boxes. Each small");
        System.out.println("boxes contain every numbers from 1 to 9, only one time each. Moreover, each rows and each columns should also be arranged in");
        System.out.println("such an order that they also contain all the numbers from 1 to 9, only one time each. In the beginning, some numbers are given");
        System.out.println("as hint to the player. The player has to fill all the boxes with correct numbers in order to win the game. Let us learn how to");
        System.out.println("how to play the game with some examples.");
        System.out.print("\nEnter \'1\' to read next or any other number to skip instructions: ");
        try {
            b = br.readLine();
            System.out.print('\u000C');
            if(b.equals("1")) {
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    This is a 9x9 sudoku board. This board is further divided into                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    9 3x3 small boxes. There are a total of 81 small boxes a player             1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    needs to fill. Out of them, some boxes are already filled and                 +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    these gives hint to the player to fill the boxes correctly.                 2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    The player while filling the boxes must keep in the mind that               3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("    a number must not repeat in each 3x3 small boxes, each row and                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    each column. Each 3x3 box, each row and each column must contain              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    all the digits between 0 and 10, and only one time each.                    4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Let us understand this briefly with an example. If you look carefully,      5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("    then you will notice that the number 7 is very frquent in the grid. Let       +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    us fill all 7s possible in this grid.                                       6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Enter \'1\' to read on or any other number to skip instructions:                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |   |   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 |   | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 |   |   |   | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                b = br.readLine();
                System.out.print('\u000C');
            }
            if(b.equals("1")) {
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                            +--   +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                            |   7 |   |   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                            |     +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                      ----> |   8 | 4 |   | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                            |     +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                            |   9 |   |   |   | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                            +--   +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                                                           ");
                System.out.println("                                                                                  |           |                            ");
                System.out.println("                                                                                  +-----------+                            ");
                System.out.println("                                                                                        A                                  ");
                System.out.println("                                                                                        |                                  ");
                System.out.println("                                                                                        |                                  ");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |   |   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 | X | 1 | |   | 6 |   | | 3 |(7)| 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 |   |   |   | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |   |   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 | X | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 | X | X | X | | 3 |(7)| 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                4 | 1 |(7)| 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |   | X |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 | X | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 | X | X | X | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   |(7)| |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 3rd column, a 7 is already present, so no more 7 in 3rd column.      3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |   | X | X | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 | X | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 | X | X | X | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(5000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |   |");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 3rd column, a 7 is already present, so no more 7 in 3rd column.      3 | 5 |   | 4 | |   |   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the remaining box, we can place 7. As one small box can contain a          +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    number only one time, so we can put no more 7 in that box.                  4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                5 |   |   |   | | 2 |   | 8 | |   |   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |   | |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                             -----> 7 | X | X | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 | X | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 | X | X | X | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(7000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   | 7 | |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |(7)|");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 3rd column, a 7 is already present, so no more 7 in 3rd column.      3 | 5 |   | 4 | |(7)|   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the remaining box, we can place 7. As one small box can contain a          +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    number only one time, so we can put no more 7 in that box.                  4 | 1 | 7 | 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Similarly, we can put 7 on the other remaining small boxes (as shown).      5 |   |   |   | | 2 |   | 8 | |(7)|   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                6 |   |   | 8 | | 7 |   |(7)| |   |   | 6 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                7 |(7)|   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 |   | 1 | |   | 6 |   | | 3 | 7 | 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 |   |   |   | | 3 | 7 | 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(7000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   |(7)| |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |(7)|");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 3rd column, a 7 is already present, so no more 7 in 3rd column.      3 | 5 |   | 4 | |(7)|   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the remaining box, we can place 7. As one small box can contain a          +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    number only one time, so we can put no more 7 in that box.                  4 | 1 |(7)| 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Similarly, we can put 7 on the other remaining small boxes (as shown).      5 |   |   |   | | 2 |   | 8 | |(7)|   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Now you can see that we already have a total of 9 7s in the grid. We know   6 |   |   | 8 | | 7 |   |(7)| |   |   | 6 |");
                System.out.println("    that a sudoku grid has a total of 9 small boxes. As a number cannot be        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    repeated within the same small box, therefore, we have completed filling      +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    all the 7s in this sudoku grid.                                             7 |(7)|   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                8 | 4 |   | 1 | |   | 6 |   | | 3 |(7)| 8 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 |   |   |   | | 3 |(7)| 4 | | 5 |   |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                Thread.sleep(10000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                    1   2   3     4   5   6     7   8   9  ");
                System.out.println("    Let us start with the first box in the bottom.                                +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                1 |   |   |(7)| |   |   |   | |   |   | 4 |");
                System.out.println("    In the 8th row, a 7 is already present, so no more 7 in 8th row.              +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 9th row, a 7 is already present, so no more 7 in 9th row.            2 |   |   | 3 | |   | 4 |   | |   |   |(7)|");
                System.out.println("    In the 2nd column, a 7 is already present, so no more 7 in 2nd column.        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the 3rd column, a 7 is already present, so no more 7 in 3rd column.      3 | 5 |   | 4 | |(7)|   |   | | 6 | 1 | 3 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    In the remaining box, we can place 7. As one small box can contain a          +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    number only one time, so we can put no more 7 in that box.                  4 | 1 |(7)| 5 | |   |   |   | |   | 3 |   |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Similarly, we can put 7 on the other remaining small boxes (as shown).      5 |   |   |   | | 2 |   | 8 | |(7)|   | 5 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Now you can see that we already have a total of 9 7s in the grid. We know   6 |   |   | 8 | | 7 |   |(7)| |   |   | 6 |");
                System.out.println("    that a sudoku grid has a total of 9 small boxes. As a number cannot be        +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    repeated within the same small box, therefore, we have completed filling      +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    all the 7s in this sudoku grid.                                             7 |(7)|   |   | |   |   |   | |   |   | 9 |");
                System.out.println("                                                                                  +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("    Just like that, we have to do with the rest of the numbers can complete     8 | 4 |   | 1 | |   | 6 |   | | 3 |(7)| 8 |");
                System.out.println("    the grid. The player who can successfully complete the grid will win.         +---+---+---+ +---+---+---+ +---+---+---+");
                System.out.println("                                                                                9 |   |   |   | | 3 |(7)| 4 | | 5 |   |   |");
                System.out.println("    Enter \'1\' to read on or any other number to skip instructions:                +---+---+---+ +---+---+---+ +---+---+---+");
                b = br.readLine();
                System.out.print('\u000C');
            }
            if(b.equals("1")) {
                System.out.println("\t\t\t\t\t\t            SUDOKU");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("SOME FACTS ABOUT THIS SUDOKU GAME:");
                System.out.println("\n  > The player cannot change the numbers already given as hints. An attempt to change these numbers will display an error");
                System.out.println("    message.");
                System.out.println("                                                                                                      +---+");
                System.out.println("  > If a player inputs a wrong number, then the number will be shown followed by a star. For example: | 2*|");
                System.out.println("                                                                                                      +---+");
                System.out.println("  > A number put by the player in the grid is decided to be correct or wrong according to the situation. This means that a");
                System.out.println("    correct number can turn wrong later acording to that condition.");
                System.out.println("\n  > You can exit the game by just typing \'100\' when it is asked. But in that case the progress will not be saved.");
                System.out.println("\n  > Do not input any character or numbers unnecessarily. This may result in errors and the program might stop, losing all");
                System.out.println("    the current progress. So be careful while giving any inputs.");
                System.out.println("\n  > To enter a number in a box, you must enter the coordinates of the box first. To enter that, you will be asked to enter");
                System.out.println("    the row and column number. You must enter these informations first. (Row numbers will be given in the left of the grid and");
                System.out.println("    column numbers will be given on the top of the grid).");
                System.out.println("\n  > To remove a number from a box, just type the same number. For example, if you want to remove a number 5 from a box, just");
                System.out.println("    enter the location of the box and then type \'5\'. The number will be removed.");
                System.out.println("\n  > We appologise for not introducing marking feature in the game. You may get it in the future updates.");
                System.out.println("\nEnter any number to start the game: ");
                b = br.readLine();
                System.out.print('\u000C');
            }
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Please restart the program to interact...");
        }
    }
}