package English.Instructions;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
public class YazyInstructions {
    public static void display()throws IOException, InterruptedException {
        long a;
        char b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        Thread.sleep(1500);
        System.out.print("\n\n\n\n\n\n\n");
        System.out.println("\t\t\t  ****          ****    ******         **************  ****          ****");
        System.out.println("\t\t\t   ****        ****    ********        **************   ****        ****     ");
        System.out.println("\t\t\t    ****      ****    ****  ****               ****     ****      ****      ");
        System.out.println("\t\t\t     ****    ****    ****    ****              ****       ****    ****       ");
        System.out.println("\t\t\t      ****  ****    ****      ****            ****         ****  ****        ");
        System.out.println("\t\t\t       ********    ****        ****          ****           ********         ");
        System.out.println("\t\t\t        ******    ****          ****        ****             ******          ");
        System.out.println("\t\t\t         ****    ********************      ****               ****           ");
        System.out.println("\t\t\t         ****    ********************     ****                ****           ");
        System.out.println("\t\t\t         ****    ****            ****    ****                 ****           ");
        System.out.println("\t\t\t         ****    ****            ****   ****                  ****           ");
        System.out.println("\t\t\t         ****    ****            ****  **************         ****           ");
        System.out.println("\t\t\t         ****    ****            ****  **************         ****           ");
        Thread.sleep(1500);
        System.out.print("\n\t\t\t\t\t\t C");
        Thread.sleep(250);
        System.out.print("r");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("a");
        Thread.sleep(250);
        System.out.print("t");
        Thread.sleep(250);
        System.out.print("e");
        Thread.sleep(250);
        System.out.print("d ");
        Thread.sleep(250);
        System.out.print("b");
        Thread.sleep(250);
        System.out.print("y ");
        Thread.sleep(500);
        System.out.print("SS ");
        Thread.sleep(500);
        System.out.print("GAMING ");
        Thread.sleep(500);
        System.out.print("STUDIOS");
        Thread.sleep(1000);
        System.out.println("\n\n\n\n\n\t\t\t\t<Enter \'1\' to check instructions or any other character to skip>");
        try {
            b = br.readLine().charAt(0);
            System.out.print('\u000C');
            if(b == '1')
                instructions();
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Restarting the program. Please wait...");
            Thread.sleep(5000);
            System.out.print('\u000C');
        }
    }
    public static void instructions()throws IOException {
        long a;
        String b;
        InputStreamReader isr = new InputStreamReader(System.in);
        BufferedReader br = new BufferedReader(isr);
        System.out.println("\t\t\t\t\t\t             YAZY");
        System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        System.out.println("Yazy is a simple board game which can be played between two, three or four people. It is played with the help of five dice.");
        System.out.println("Each player gets chance to play one after another, just like ludo or chess. The player has to throw the five dice at the same");
        System.out.println("time. Based on the combination of the numbers one get in the dice and the criterias fulfilled, he/she gets points. Let us take");
        System.out.println("a detailed look on how to play.");
        System.out.print("\nEnter \'1\' to read next or any other number to skip instructions: ");
        try {
            b = br.readLine();
            System.out.print('\u000C');
            if(b.equals("1")) {
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X O + * # |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    -     -     -     -     -     -     -     -     -     -     -                 |   TOTAL   |  00  |  00  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(30000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         | O   O |   | O   O |   |       |   | O   O |   | O   O |                | X X X O O |      |      |      |      |");
                System.out.println("         |       |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         | O   O |   | O   O |   |       |   | O   O |   | O   O |                | X O + * # |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    1     0     0     4     15    0     20    0     0     0     0                 |   TOTAL   |  00  |  00  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X O + * # |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    -     -     -     -     -     -     -     -     -     -     -                 |   TOTAL   |  20  |  00  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         | O     |   | O     |   | O   O |   |       |   | O   O |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |   O   |   |   O   |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |     O |   |     O |   | O   O |   |       |   | O   O |                | X O + * # |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    1     2     3     4     5     0     0     0     0     40    0                 |   TOTAL   |  20  |  00  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    -     -     -     -     -     -     -     -     -     -     -                 |   TOTAL   |  20  |  40  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   | O O O |   | O O O |   | O   O |   | O O O |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |       |   | O O O |   | O O O |   | O   O |   | O O O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    1     0     0     4     0     18    23    0     0     0     0                 |   TOTAL   |  20  |  40  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+           +--       --+              |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("         |       |   | O O O |   | O O O |   | O   O |   | O O O |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |       |   | O O O |   | O O O |   | O   O |   | O O O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+           +--       --+              | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    1     0     0     4     0     18    23    0     0     0     0                 |   TOTAL   |  20  |  40  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+           +--       --+              |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("         | O O O |   | O O O |   | O O O |   | O O O |   | O O O |                | X X X O O |      |      |      |      |");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         | O O O |   | O O O |   | O O O |   | O O O |   | O O O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+           +--       --+              | X X X X X |      |      |      |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    0     0     0     0     0     36    36    36    0     0     50                |   TOTAL   |  20  |  40  |  00  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    -     -     -     -     -     -     -     -     -     -     -                 |   TOTAL   |  20  |  40  |  50  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         | O     |   | O   O |   | O   O |   | O   O |   | O     |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |     O |   | O   O |   | O   O |   | O   O |   |     O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    0     2     3     12    0     0     17    0     0     0     0                 |   TOTAL   |  20  |  40  |  50  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+--       --+              |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("         | O     |   | O   O |   | O   O |   | O   O |   | O     |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |     O |   | O   O |   | O   O |   | O   O |   |     O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+         --+              | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    0     2     3     12    0     0     17    0     0     0     0                 |   TOTAL   |  20  |  40  |  50  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+--       --+              |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("         |       |   | O   O |   | O   O |   | O   O |   | O     |                | X X X O O |      |      |      |      |");
                System.out.println("         |   O   |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |       |   | O   O |   | O   O |   | O   O |   |     O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+         --+              | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    1     2     0     12    0     0     15    0     0     0     0                 |   TOTAL   |  20  |  40  |  50  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+--       --+              |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("         | O     |   | O   O |   | O   O |   | O   O |   | O     |                | X X X O O |      |      |      |      |");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                +-----------+------+------+------+------+");
                System.out.println("         |     O |   | O   O |   | O   O |   | O   O |   |     O |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+ | +-------+ | +-------+ | +-------+ | +-------+ |              +-----------+------+------+------+------+");
                System.out.println("                   +--       --+--       --+--       --+         --+              | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    0     4     0     12    0     0     16    0     25    0     0                 |   TOTAL   |  20  |  40  |  50  |  00  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                Thread.sleep(2000);
                System.out.print('\u000C');
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    This is how a yazy (Four Players) board looks like:                           |     1     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    A player is given five dice. He needs to roll all the dice at once.           |     2     |      |      |      |      |");
                System.out.println("    He/she gets points on the combinations of the dice. Based on the              +-----------+------+------+------+------+");
                System.out.println("    combinations, one gets 11 different points based on the conditions            |     3     |      |      |      |      |");
                System.out.println("    of the criterias on the board. The player needs to choose the best            +-----------+------+------+------+------+");
                System.out.println("    point. He/she gets three consequetive chances of rolling the dice and         |     4     |      |      |      |      |");
                System.out.println("    may pause a dice from rolling further and let a dice to roll again            +-----------+------+------+------+------+");
                System.out.println("    to acquire the best combinations.                                             |     5     |      |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("    The next player gets his/her turn after the previous player's turn is         |     6     |      |      |      |      |");
                System.out.println("    over. The player to score the highest point at the end wins.                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |   X X X   |  20  |      |      |      |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.println("                                                                                  |  X X X X  |      |      |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X X X O O |      |      |      |  25  |");
                System.out.println("         |   O   |   |   O   |   |   O   |   |   O   |   |   O   |                +-----------+------+------+------+------+");
                System.out.println("         |       |   |       |   |       |   |       |   |       |                | X O + * # |      |  40  |      |      |");
                System.out.println("         +-------+   +-------+   +-------+   +-------+   +-------+                +-----------+------+------+------+------+");
                System.out.println("                                                                                  | X X X X X |      |      |  50  |      |");
                System.out.println("    A     B     C     D     E     F     G     H     I     J     K                 +-----------+------+------+------+------+");
                System.out.println("    -     -     -     -     -     -     -     -     -     -     -                 |   TOTAL   |  20  |  40  |  50  |  25  |");
                System.out.println("                                                                                  +-----------+------+------+------+------+");
                System.out.print("    Enter \'1\' to read on or any other number to skip instructions: ");
                b = br.readLine();
                System.out.print('\u000C');
            }
            if(b.equals("1")) {
                System.out.println("\t\t\t\t\t\t             YAZY");
                System.out.println("\t\t\t\t\t\t created by SS GAMING STUDIOS");
                System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
                System.out.println("Now let us take a look at the 11 criterias:");
                System.out.println("");
                System.out.println("    You will get the sum                 +-----------+------+------+------+------+");
                System.out.println("      of \'1\'s you get on  ------------>  |     1     |      |      |      |      |");
                System.out.println("   the dice as the point                 +-----------+------+------+------+------+                 You will get the sum");
                System.out.println("                                         |     2     |      |      |      |      |  <------------  of \'2\'s you get on");
                System.out.println("    You will get the sum                 +-----------+------+------+------+------+                 the dice as the point");
                System.out.println("      of \'3\'s you get on  ------------>  |     3     |      |      |      |      |");
                System.out.println("   the dice as the point                 +-----------+------+------+------+------+                 You will get the sum");
                System.out.println("                                         |     4     |      |      |      |      |  <------------  of \'4\'s you get on");
                System.out.println("    You will get the sum                 +-----------+------+------+------+------+                 the dice as the point");
                System.out.println("      of \'4\'s you get on  ------------>  |     5     |      |      |      |      |");
                System.out.println("   the dice as the point                 +-----------+------+------+------+------+                 You will get the sum");
                System.out.println("                                         |     6     |      |      |      |      |  <------------  of \'6\'s you get on");
                System.out.println("    You will get the sum                 +-----------+------+------+------+------+                 the dice as the point");
                System.out.println(" of all five dice if any  ------------>  |   X X X   |      |      |      |      |");
                System.out.println("  three numbers are same                 +-----------+------+------+------+------+                 You will get the sum");
                System.out.println("                                         |  X X X X  |      |      |      |      |  <------------  of all five dice if any");
                System.out.println("  You will get 25 points                 +-----------+------+------+------+------+                 four numbers are same");
                System.out.println(" points if three numbers  ------------>  | X X X O O |      |      |      |      |");
                System.out.println(" are same and the remai-                 +-----------+------+------+------+------+                 You will get 40 points");
                System.out.println("  ning two are also same                 | X O + * # |      |      |      |      |  <------------  if all five numbers are");
                System.out.println("                                         +-----------+------+------+------+------+                 in series");
                System.out.println("  You will get 50 points       +------>  | X X X X X |      |      |      |      |");
                System.out.println(" if all five numbers are  -----+         +-----------+------+------+------+------+");
                System.out.println("                    same                 |   TOTAL   |  00  |  00  |  00  |  00  |  <------------  This shows your total");
                System.out.println("                                         +-----------+------+------+------+------+                 points");
                System.out.println("\nEnter any number to start the game: ");
                b = br.readLine();
                System.out.print('\u000C');
            }
        }
        catch(Exception ex) {
            System.out.println("An error occured!");
            System.out.println("Exception: "+ ex);
            System.out.print("Please restart the program to interact...");
        }
    }
}